# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='collaborators',
            field=models.ManyToManyField(related_name='documents', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='document',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.Collection'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='document',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.Document'),
        ),
        migrations.AddField(
            model_name='document',
            name='stars',
            field=models.ManyToManyField(related_name='starred', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='document',
            name='views',
            field=models.ManyToManyField(related_name='viewed', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='collection',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='profiles.Profile'),
        ),
    ]
