# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='library',
            name='files',
            field=models.ManyToManyField(related_name='libraries', to='papers.File'),
        ),
        migrations.AddField(
            model_name='file',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='papers.Paper'),
        ),
    ]
